class Path:
    solution_list = []
    
    def game1(self):
        self.solution_list.append((1,3,"s"))
        self.solution_list.append((2,5,"w"))
        self.solution_list.append((0,4,"s"))
        self.solution_list.append((3,4,"n"))
        self.solution_list.append((0,2,"e"))
        self.solution_list.append((0,4,"s"))
        self.solution_list.append((5,4,"n"))
        self.solution_list.append((4,6,"w"))
        self.solution_list.append((4,3,"e"))
        self.solution_list.append((2,6,"s"))
        self.solution_list.append((4,6,"w"))
        self.solution_list.append((4,1,"e"))
        self.solution_list.append((6,2,"n"))
        self.solution_list.append((3,2,"s"))
        self.solution_list.append((6,4,"w"))
        self.solution_list.append((6,2,"n"))
        self.solution_list.append((1,2,"s"))
        self.solution_list.append((2,0,"e"))
        self.solution_list.append((2,3,"w"))
        self.solution_list.append((4,0,"n"))
        self.solution_list.append((2,0,"e"))
        self.solution_list.append((4,3,"w"))
        self.solution_list.append((4,1,"n"))
        self.solution_list.append((2,1,"e"))
        self.solution_list.append((2,3,"e"))
        self.solution_list.append((2,5,"s"))
        self.solution_list.append((4,5,"w"))
        self.solution_list.append((3,3,"e"))
        self.solution_list.append((5,3,"n"))
        self.solution_list.append((3,2,"e"))
        self.solution_list.append((3,5,"w"))
        return self.solution_list
        
